name: 'Build Reporter'
description: 'Report build information in workflow summary'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  build-reports-artifacts-path:
    description: 'Path where to find build reports'
    required: false
  forks-only:
    description: 'Whether the report should be added for forks only'
    required: false
runs:
  using: "composite"
  steps:
    - run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      shell: bash
    - run: ~/.jbang/bin/jbang --repos 'https://s01.oss.sonatype.org/content/repositories/snapshots/' --repos 'mavencentral' io.quarkus.bot:action-build-reporter:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
